export const SET_TABLE_DATA = 'SET_TABLE_DATA';
export const DELETE_TABLE_ID = 'DELETE_TABLE_ID';
export const EDD_TABLE_INPUT_VALUE = 'EDD_TABLE_INPUT_VALUE';
export const SORT_ID_DATA = 'SORT_ID_DATA';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';